In [1]:
import pandas as pd
import matplotlib.pyplot as plt
from preprocessing_v4 import data_preprocessing
from preprocessing_v4 import draw_graph

pd.set_option('display.max_columns', 60)
pd.set_option('display.max_rows', 60)
pd.set_option('mode.chained_assignment',  None)

plt.rc('font',family='malgun gothic')

# 국가교통 데이터 오픈마켓
bus_info_data_by_day = pd.read_csv('./data/대전시_버스_일일_정보_데이터.csv', sep = "|") # 대전시 버스 일일 정보 데이터
bus_speed_data = pd.read_csv('./data/대전시_버스_통행_속도_데이터.csv', sep = "|") # 대전시 버스 통행 속도 데이터
bus_route_statistic_data = pd.read_csv('./data/대전시_버스_노선_운행_통계_데이터.csv', sep = "|") # 대전시 버스 노선 운행 통계 데이터
bus_card_data = pd.read_csv('./data/대전시_버스_교통카드거래_이력_데이터.csv', sep = "|") # 대전시 버스 카드 거래 이력 데이터
speed_comparison_data = pd.read_csv('./data/대전시_버스전용차로_승용차구간_속도비교_데이터.csv', sep = "|") # 대전시 버스전용차로 승용차구간 속도비교 데이터

bus_info_data_by_day.drop(labels = ['ETL_TYPE','ETL_DATE'], axis =  1, inplace = True)
bus_speed_data.drop(labels = ['ETL_TYPE','ETL_DATE'], axis =  1, inplace = True)
bus_route_statistic_data.drop(labels = ['ETL_TYPE','ETL_DATE'], axis =  1, inplace = True)
bus_card_data.drop(labels = ['ETL_TYPE','ETL_DATE'], axis =  1, inplace = True)

# 대전 교통 빅데이터 플랫폼
route_curve = pd.read_csv('./data/route_curve.csv', encoding = 'cp949')
route_curve = route_curve.iloc[:,:5]

# 공공데이터포털
getrouteinfoall = pd.read_csv('./data/getRouteInfoAll.csv', encoding = 'cp949', index_col = 0) # 전체 노선 기본정보 조회
getstationbyrouteall = pd.read_csv('./data/getStationByRouteAll.csv', encoding = 'cp949', index_col = 0) # 전체노선별경유정류소 정보 조회

# 정류장 데이터
bus_sttn = pd.read_csv('./data/bus_sttn.csv')

# 스마트카드 데이터
smart_card_data = pd.read_csv('./data/smart_card_data.csv')

In [2]:
smart_card_data = data_preprocessing.smart_card_preprocessing(smart_card_data)
df = smart_card_data.copy()
df.head(3)

,CARD_NO,TRANSACTION_ID,TR_MEANS_TYPE,TRANSF_CNT,BUS_ROUTE_ID,BUS_CO_ID,BUS_CAR_ID,USR_TYPE,GETON_BUS_STTN_ID,GETOFF_BUS_STTN_ID,YSR_CNT,GETON_PAY,GETOFF_PAY,GETON_DATETIME,GETOFF_DATETIME,GETON_TIME,GETOFF_TIME
1,540104832,17,675,0,30300083,130010001,130759426,1,8001279,8001538,1,1250,0,2022-04-01 09:25:42,2022-04-01 09:37:29,9,9
3,741520439,1,676,0,30300043,130010015,130759609,1,8001428,8002717,1,1250,0,2022-04-01 07:32:15,2022-04-01 07:52:54,7,7
4,759623940,1,676,0,30300071,130010009,130759147,1,8001990,8001464,1,1250,0,2022-04-01 19:10:41,2022-04-01 19:15:39,19,19

하위 이용 노선 시각화 코드

In [98]:
# bus_route_counts_df = pd.DataFrame({'BUS_ROUTE_ID': df['BUS_ROUTE_ID'].value_counts().index, 'COUNT': df['BUS_ROUTE_ID'].value_counts().values})
# # bus_route_counts_df = bus_route_counts_df.sort_values('COUNT', ascending = True).head(16)

In [99]:
# getrouteinfoall_df = getrouteinfoall[['ROUTE_CD','ROUTE_NO']]
# merged_data =bus_route_counts_df.merge(getrouteinfoall_df, left_on = 'BUS_ROUTE_ID', right_on = 'ROUTE_CD')

In [58]:
# merged_data = merged_data[merged_data['ROUTE_NO']!='33-1']
# merged_data = merged_data[merged_data['ROUTE_NO']!='33-2']
# merged_data = merged_data[merged_data['ROUTE_NO']!='66']
# merged_data = merged_data[merged_data['ROUTE_NO']!='20']
# merged_data = merged_data[merged_data['ROUTE_NO']!='특구1']
# merged_data = merged_data[merged_data['ROUTE_NO']!='1']

In [60]:
# import pandas as pd
# import seaborn as sns
# import matplotlib.pyplot as plt

# sns.set(style="whitegrid")

# plt.figure(figsize=(12, 6))
# plt.rc('font',family='malgun gothic')
# sns.barplot(x='ROUTE_NO', y='COUNT', data=merged_data, palette='Blues_d')
# plt.xlabel('버스 노선 ID')
# plt.ylabel('이용 횟수')
# plt.title('버스 노선별 이용 횟수')
# plt.xticks(rotation = 0)
# plt.tight_layout()
# plt.show()

상위 이용 버스 노선 5개 시각화

In [16]:
# ### 상위 이용 버스 노선 5개
# # 102번 버스
# route_30300037 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300037]

# # 311번 버스
# route_30300055 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300055]

# # 201번 버스
# route_30300051 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300051]

# # 301번 버스
# route_30300054 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300054]

# # 106번 버스
# route_30300041 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300041]

In [15]:
# import pydeck as pdk
# import geopandas as gpd

# # 102번 버스 노선 시각화
# layer_30300037 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300037,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[255, 0, 0, 200],  # 빨간색 (RGB 및 투명도)
#     get_radius=100,
#     pickable=True,
# )

# # 311번 버스 노선 시각화
# layer_30300055 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300055,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[255, 150, 0, 200],  # 주황색
#     get_radius=100,
#     pickable=True,
# )

# # 201번 버스 노선 시각화
# layer_30300051 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300051,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[255, 200, 0, 200],  # 노란색
#     get_radius=100,
#     pickable=True,
# )

# # 301번 버스 노선 시각화
# layer_30300054 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300054,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[0, 100, 50, 200],   # 초록색
#     get_radius=100,
#     pickable=True,
# )

# # 105번 버스 노선 시각화
# layer_30300041 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300041,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[0, 50, 200, 200],  # 파란색
#     get_radius=100,
#     pickable=True,
# )


# # PyDeck 맵 생성
# view_state = pdk.ViewState(latitude=36.35, longitude=127.38, zoom=11)
# r = pdk.Deck(layers=[layer_30300037, layer_30300055,layer_30300051,layer_30300054,layer_30300041], initial_view_state=view_state)
# # r.to_html('top5_route.html')

하위 이용 버스 노선 5개 시각화

In [96]:
# ### 하위 이용 버스 노선 5개
# # 622번 버스
# route_30300144 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300144]

# # 212번 버스
# route_30300127 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300127]

# # 213번 버스
# route_30300146 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300146]

# # 712번 버스
# route_30300092 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300092]

# # 313번 버스
# route_30300057 = getstationbyrouteall[getstationbyrouteall['ROUTE_CD']==30300057]

In [97]:
# import pydeck as pdk
# import geopandas as gpd

# # 622번 버스 노선 시각화
# layer_30300144 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300144,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=([255, 200, 200, 170]),  # 빨간색 (RGB 및 투명도)
#     get_radius=100,
#     pickable=True,
# )

# # 212번 버스 노선 시각화
# layer_30300127 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300127,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[255, 200, 150, 170],  # 주황색
#     get_radius=100,
#     pickable=True,
# )

# # 213번 버스 노선 시각화
# layer_30300146 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300146,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[255, 255, 200, 170],  # 노란색
#     get_radius=100,
#     pickable=True,
# )

# # 712번 버스 노선 시각화
# layer_30300092 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300092,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[200, 250, 200, 170],   # 초록색
#     get_radius=100,
#     pickable=True,
# )

# # 313번 버스 노선 시각화
# layer_30300057 = pdk.Layer(
#     "ScatterplotLayer",
#     data=route_30300057,
#     get_position=["GPS_LONG", "GPS_LATI"],
#     get_color=[150, 200, 250, 170],  # 파란색
#     get_radius=100,
#     pickable=True,
# )


# # PyDeck 맵 생성
# view_state = pdk.ViewState(latitude=36.35, longitude=127.38, zoom=11)
# r = pdk.Deck(layers=[layer_30300144,layer_30300127,layer_30300146,layer_30300092,layer_30300057], initial_view_state=view_state)

# r.to_html('under5_route.html')

승차 시간대별 이용량 그래프

In [104]:
# import matplotlib.pyplot as plt
# from matplotlib.ticker import MultipleLocator

# # GETON_TIME별 이용량 계산
# geton_time_counts = df['GETON_TIME'].value_counts().sort_index()

# # 그래프 그리기
# plt.figure(figsize=(10, 6))
# plt.bar(geton_time_counts.index, geton_time_counts.values, color='skyblue')
# plt.xlabel('GETON_TIME')
# plt.ylabel('이용량')
# plt.title('승차 시간대별 이용량 그래프')

# # x축 눈금을 정수로 표시하기 위한 설정
# plt.gca().xaxis.set_major_locator(MultipleLocator(base=1))

# plt.xticks(rotation=0)
# plt.grid(True, axis = 'y')
# plt.show()

하차 시간대별 이용량 그래프

In [34]:
# import matplotlib.pyplot as plt
# from matplotlib.ticker import MultipleLocator

# # GETON_TIME별 이용량 계산
# getoff_time_counts = df['GETOFF_TIME'].value_counts().sort_index()

# # 그래프 그리기
# plt.figure(figsize=(10, 6))
# plt.bar(getoff_time_counts.index, getoff_time_counts.values, color='lightpink')
# plt.xlabel('GETOFF_TIME')
# plt.ylabel('이용량')
# plt.title('하차 시간대별 이용량 그래프')

# # x축 눈금을 정수로 표시하기 위한 설정
# plt.gca().xaxis.set_major_locator(MultipleLocator(base=1))

# plt.xticks(rotation=0)
# plt.grid(True, axis = 'y')
# plt.show()

In [25]:
df.head(3)

,CARD_NO,TRANSACTION_ID,TR_MEANS_TYPE,TRANSF_CNT,BUS_ROUTE_ID,BUS_CO_ID,BUS_CAR_ID,USR_TYPE,GETON_BUS_STTN_ID,GETOFF_BUS_STTN_ID,YSR_CNT,GETON_PAY,GETOFF_PAY,GETON_DATETIME,GETOFF_DATETIME,GETON_TIME,GETOFF_TIME
1,540104832,17,675,0,30300083,130010001,130759426,1,8001279,8001538,1,1250,0,2022-04-01 09:25:42,2022-04-01 09:37:29,9,9
3,741520439,1,676,0,30300043,130010015,130759609,1,8001428,8002717,1,1250,0,2022-04-01 07:32:15,2022-04-01 07:52:54,7,7
4,759623940,1,676,0,30300071,130010009,130759147,1,8001990,8001464,1,1250,0,2022-04-01 19:10:41,2022-04-01 19:15:39,19,19

In [141]:
# def station_data_for_graph_geton(exdata,bus_sttn, route_id):
#     exdata = exdata[exdata['BUS_ROUTE_ID']==route_id]
#     value_counts_df = exdata['GETON_BUS_STTN_ID'].value_counts().reset_index()
#     value_counts_df.columns = ['GETON_BUS_STTN_ID', 'count']
#     exdata = value_counts_df.merge(bus_sttn, left_on = 'GETON_BUS_STTN_ID', right_on = 'bus_sttn_id')
#     return exdata

In [99]:
getrouteinfoall[getrouteinfoall['ROUTE_NO']=='106']['ROUTE_CD']

32    30300041
Name: ROUTE_CD, dtype: int64

In [140]:
# # 30300037 102번
# df_30300037 = station_data_for_graph_geton(df,bus_sttn, 30300037)
# # 30300055 311번
# df_30300055 = station_data_for_graph_geton(df,bus_sttn, 30300055)
# # 30300051 201번
# df_30300051 = station_data_for_graph_geton(df,bus_sttn, 30300051)
# # 30300054 301번
# df_30300054 = station_data_for_graph_geton(df,bus_sttn, 30300054)
# # 30300041 106번
# df_30300041 = station_data_for_graph_geton(df,bus_sttn, 30300041)

In [136]:
# import pydeck as pdk
# # PyDeck 맵 생성
# view_state = pdk.ViewState(latitude=36.35, longitude=127.38, zoom=11)

# # ScatterplotLayer를 사용하여 시각화
# layer_30300037 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300037,
#     get_position=["posy", "posx"],
#     get_color=[255, 0, 0, 150],  # 빨간색 (RGB 및 투명도)
#     get_radius="count/10",
#     pickable=True,
# )

# layer_30300055 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300055,
#     get_position=["posy", "posx"],
#     get_color=[255, 150, 0, 200],
#     get_radius="count/10",
#     pickable=True,
# )

# layer_30300051 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300051,
#     get_position=["posy", "posx"],
#     get_color=[255, 200, 0, 200],  # 노란색
#     get_radius="count/10",
#     pickable=True,
# )

# layer_30300054 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300054,
#     get_position=["posy", "posx"],
#     get_color=[0, 100, 50, 200],   # 초록색
#     get_radius="count/10",
#     pickable=True,
# )

# layer_30300041 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300041,
#     get_position=["posy", "posx"],
#     get_color=[0, 50, 200, 200],  # 파란색
#     get_radius="count/10",
#     pickable=True,
# )

# # PyDeck Deck 생성
# r = pdk.Deck(layers=[layer_30300037, layer_30300055,layer_30300051,layer_30300054,layer_30300041], initial_view_state=view_state)
# # PyDeck 그래프를 HTML로 출력
# r.to_html('bus_stations_map_geton.html')

In [137]:
# def station_data_for_graph_getoff(exdata,bus_sttn, route_id):
#     exdata = exdata[exdata['BUS_ROUTE_ID']==route_id]
#     value_counts_df = exdata['GETOFF_BUS_STTN_ID'].value_counts().reset_index()
#     value_counts_df.columns = ['GETOFF_BUS_STTN_ID', 'count']
#     exdata = value_counts_df.merge(bus_sttn, left_on = 'GETOFF_BUS_STTN_ID', right_on = 'bus_sttn_id')
#     return exdata

In [124]:
getrouteinfoall[getrouteinfoall['ROUTE_NO']=='313']['ROUTE_CD']

47    30300057
Name: ROUTE_CD, dtype: int64

In [138]:
# # 30300144 622번
# df_30300144 = station_data_for_graph_geton(df,bus_sttn, 30300144)
# # 30300127 212번
# df_30300127 = station_data_for_graph_geton(df,bus_sttn, 30300127)
# # 30300146 213번
# df_30300146 = station_data_for_graph_geton(df,bus_sttn, 30300146)
# # 30300092 712번
# df_30300092 = station_data_for_graph_geton(df,bus_sttn, 30300092)
# # 30300057 313번
# df_30300057 = station_data_for_graph_geton(df,bus_sttn, 30300057)

In [139]:
# import pydeck as pdk
# import geopandas as gpd

# # 622번 버스 노선 시각화
# layer_30300144 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300144,
#     get_position=["posy", "posx"],
#     get_color=[255, 0, 0, 150],  # 빨간색 (RGB 및 투명도)
#     get_radius="count/2",
#     pickable=True,
# )

# # 212번 버스 노선 시각화
# layer_30300127 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300127,
#     get_position=["posy", "posx"],
#     get_color=[255, 150, 0, 200],
#     get_radius="count/2",
#     pickable=True,
# )

# # 213번 버스 노선 시각화
# layer_30300146 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300146,
#     get_position=["posy", "posx"],
#     get_color=[255, 200, 0, 200],  # 노란색
#     get_radius="count/2",
#     pickable=True,
# )

# # 712번 버스 노선 시각화
# layer_30300092 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300092,
#     get_position=["posy", "posx"],
#     get_color=[0, 100, 50, 200],   # 초록색
#     get_radius="count/2",
#     pickable=True,
# )

# # 313번 버스 노선 시각화
# layer_30300057 = pdk.Layer(
#     "ScatterplotLayer",
#     data=df_30300057,
#     get_position=["posy", "posx"],
#     get_color=[0, 50, 200, 200],  # 파란색
#     get_radius="count/2",
#     pickable=True,
# )


# # PyDeck 맵 생성
# view_state = pdk.ViewState(latitude=36.35, longitude=127.38, zoom=11)
# r = pdk.Deck(layers=[layer_30300144,layer_30300127,layer_30300146,layer_30300092,layer_30300057], initial_view_state=view_state)

# r.to_html('bus_stations_map_getoff.html')