In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.ticker as ticker
from processing import *

pd.set_option('display.max_columns', 50)
pd.set_option('display.max_rows', 50)
pd.set_option('mode.chained_assignment',  None)

get_in_off_merged_data = pd.read_csv('./data/get_in_off_bus.csv')

# getrouteinfoall
getrouteinfoall = pd.read_csv('./data/getRouteInfoAll.csv', encoding = 'cp949', index_col = 0)
getrouteinfoall_df = getrouteinfoall[['ROUTE_CD','ROUTE_NO']]

### gestationbyrouteall
getstationbyrouteall = pd.read_csv('./data/getStationByRouteAll.csv', encoding = 'cp949', index_col = 0)
getstationbyrouteall_df1 = getstationbyrouteall[['ROUTE_CD','BUSSTOP_SEQ','BUSSTOP_TP','GPS_LATI','GPS_LONG']]
getstationbyrouteall_df2 = getstationbyrouteall[['ROUTE_CD','BUS_STOP_ID','BUSSTOP_SEQ','BUSSTOP_TP','GPS_LATI','GPS_LONG']]

In [10]:
get_in_off_merged_data_copy = data_preprocessing.get_in_off_merged_data_preprocessing(get_in_off_merged_data)
get_in_off_merged_data_copy.head()

,노선,정류장순번,정류장,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,DAY
0,102,1,수통골기점지,0,0,0,0,0,0,0,0,0,7,0,0,0,0,0,0,0,6,0,1
1,102,2,수통골삼거리,1,2,3,6,5,4,4,5,7,9,13,8,8,8,3,5,4,1,0,1
2,102,3,한밭대학교,1,3,6,11,9,9,27,18,16,26,40,45,32,33,9,20,12,16,0,1
3,102,4,삼성화재연수원,0,0,3,9,0,10,30,21,12,33,35,49,34,34,10,26,24,16,0,1
4,102,5,하우스토리/신협연수원,2,5,17,14,12,14,31,22,18,36,40,52,36,37,11,25,26,10,0,1

---

# 히트맵 그리기

In [11]:
# 각 노선별로 평균 데이터프레임 생성하는 코드 ex) AVERAGE_DATA_102 : 102번 버스의 평균값
bus_numbers = [102, 103, 105, 106, 108, 115, 119, 201, 211, 301, 311, 314, 511, 603, 604, 605, 613, 615, 703, 704, 705, 706, 802]
average_data_dict = {}

for bus_number in bus_numbers:
    average_data = make_data.bus_average_data(get_in_off_merged_data_copy, bus_number)
    average_data_dict[bus_number] = average_data

for bus_number in bus_numbers:
    df_name = f"AVERAGE_DATA_{bus_number}"
    globals()[df_name] = average_data_dict[bus_number]

In [12]:
# 필요한 노선만 필터링한 뒤, int형으로 변환
bus_numbers = ['102', '103', '105', '106', '108', '115', '119', '201', '211', '301', '311', '314', '511', '603', '604', '605', '613', '615', '703', '704', '705', '706', '802']
ROUTE_BUS_NUMBER = getrouteinfoall_df[getrouteinfoall_df['ROUTE_NO'].isin(bus_numbers)]
ROUTE_BUS_NUMBER['ROUTE_NO'] = ROUTE_BUS_NUMBER['ROUTE_NO'].astype(int)

In [13]:
bus_numbers = [102, 103, 105, 106, 108, 115, 119, 201, 211, 301, 311, 314, 511, 603, 604, 605, 613, 615, 703, 704, 705, 706, 802] # 위에서 str타입으로 불러왔으니 다시 불러오기

for bus_number in bus_numbers: # 노선(버스)별로 BUSSTOP_TP를 필터링해줌
    variable_name = f"BUS_{bus_number}_BUSSTOP_TP" # BUS_102_BUSSTOP_TP
    globals()[variable_name] = make_data.get_bus_stop_tp(getstationbyrouteall_df1, ROUTE_BUS_NUMBER, bus_number)

In [14]:
# 각 버스별로 상/하행 데이터 생성
for bus_number in bus_numbers:
    average_data = globals().get(f'AVERAGE_DATA_{bus_number}')  # ex: AVERAGE_DATA_102
    busstop_tp_data = globals().get(f'BUS_{bus_number}_BUSSTOP_TP')  # ex: BUS_102_BUSSTOP_TP
    
    bus_number_str = str(bus_number).zfill(3)  # 버스번호를 3자리로 맞춤
    bus_name = f'BUS_{bus_number_str}'
    
    # 상/하행 데이터 생성
    up_data, down_data = make_data.final_data(average_data, busstop_tp_data)
    # 데이터 저장
    globals()[f'{bus_name}_UP'] = up_data
    globals()[f'{bus_name}_DOWN'] = down_data

In [10]:
# def plot_bus_heatmap(bus_number, direction):
#     plt.rc('font', family='malgun gothic')
#     plt.figure(figsize=(20, 20))
    
#     if direction == 'UP':
#         heatmap_data = globals().get(f'BUS_{bus_number}_UP')
#     elif direction == 'DOWN':
#         heatmap_data = globals().get(f'BUS_{bus_number}_DOWN')
    
#     heatmap_data = heatmap_data.iloc[:, :19]  # 좌표 데이터 제거 후 히트맵 표시
    
#     sns.heatmap(heatmap_data, annot=True, fmt='.1f', vmin=0, vmax=60)
#     plt.title(f'{bus_number}번 {direction} 버스 히트맵')
#     plt.xlabel('시간대')
#     plt.ylabel('정류장순번')

#      # 그래프를 이미지 파일로 저장
#     image_path = f'./IMAGE_FILE_3/{bus_number}_{direction}_heatmap.png'
#     plt.savefig(image_path, bbox_inches='tight')

#     plt.show()

In [9]:
# # 버스 전체 히트맵 저장
# bus_numbers = [102, 103, 105, 106, 108, 115, 119, 201, 211, 301, 311, 314, 511, 603, 604, 605, 613, 615, 703, 704, 705, 706, 802]
# up_down = ['UP', 'DOWN']

# def plot_and_save_heatmaps():
#     for bus_number in bus_numbers:
#         for direction in up_down:
#             plot_bus_heatmap(bus_number, direction)
#             print(f'{bus_number}번 {direction} 버스 히트맵 생성 및 저장 완료.')

# # 이미지 파일로 저장
# plot_and_save_heatmaps()

## folium heatmapwithtime

### 출퇴근 시간대 노선
> 105번, 604번, 605번, 703번, 705번

In [8]:
import pandas as pd
import folium
from folium import plugins
from sklearn.preprocessing import MinMaxScaler

minMaxScaler = MinMaxScaler()

BUS_NUM_6_TO_22 = [704, 705, 802]
UP_DOWN_6_TO_22 = ['UP', 'DOWN']
time_series = ['6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '20', '21', '22']

for bus_num in BUS_NUM_6_TO_22:
    for up_down in UP_DOWN_6_TO_22:
        # min-max 스케일링
        bus_num_str = str(bus_num).zfill(3) # 3자리 숫자로 맞춰줌
        data_to_scale = eval(f'BUS_{bus_num_str}_{up_down}.iloc[:,:19]')  # Extract the data for scaling
        scaled_data = minMaxScaler.fit_transform(data_to_scale)  # Fit and transform the scaler
        BUS_minMaxScaled = pd.DataFrame(scaled_data, index=data_to_scale.index, columns=data_to_scale.columns)
        BUS_concat = pd.concat([BUS_minMaxScaled, eval(f'BUS_{bus_num_str}_{up_down}.iloc[:, 19:]')], axis=1)
        
        # 히트맵 데이터 생성
        heat_data = [[[row['GPS_LATI'], row['GPS_LONG'], row[time]] for index, row in BUS_concat.iterrows()] for time in time_series]
        
        # 히트맵 folium 지도 생성 및 저장
        m = folium.Map(location=[36.3504119, 127.3845475], zoom_start=12)
        heat_map = plugins.HeatMapWithTime(heat_data, index=[time for time in time_series], auto_play=False, radius=20, max_opacity=1, gradient={0.1: 'blue', 0.3: 'lime', 0.6: 'yellow', 1: 'red'})
        heat_map.add_to(m)
        m.save(f'./HEATMAP_HTML_FILE_4/BUS_{bus_num_str}_{up_down}.html')
        # await map_to_png(f'./HEATMAP_CAPTURE/BUS_{bus_num_str}_{up_down}', m) # 출처 : https://yeomss.tistory.com/276

        # 색상 다르게 하려면 gradient = {0.2: '#FBD973',  0.4: '#fa782f', 0.75: '#F16578', 1: '#782890'})